language: java
dist: trusty
jdk:
  - openjdk8
  - openjdk11
env: NODE_VERSION=10.2.1
before_install: nvm install $NODE_VERSION

jobs:
  include:
    - stage: "Debug adapter"
      name: "Tests"
      script: ./gradlew :adapter:test -i
    - name: "Executable"
      script: ./gradlew :adapter:installDist
    - stage: "Deploy"
      before_deploy: ./gradlew :adapter:distZip
      deploy:
        provider: releases
        api_key:
          secure: "hJNQFT/1o+ywvPT/zFk2/YzK5rBU7gYIG7RXH4TPEZVQmbf//tAUkTdKuvPyEKsrFxy2CRfgOYpWrrRlVOKFlavyjbvOmwfOau0cI+MiXAd64RM0QhglL7j+ZszankVJXuBvTb8WVJ/GGgyc+mXFb+4BX3L9GbgMDokT2lgGo5cDxuRgNlLa9Etov3GtrDSCAJrLwbtPhXErp7L27YwS2GydRv84T8GtQIIgEkccLRK0nTIka56zLC0znzJ/OQ2M+TjfQBQghRppx3IV2XKayIqcXbpuh7IjAbXI1jms0awX0tTplCrr5kBmyRafVjWi6K/5nibJ6UlHszvS7Txj6K4ggrNUGhbrpE1LiOguQV4cJmPrZvX2UfezA2QddmaMHh06ckIWtBd3CEOYIylYhLfOV5Uelo/ZwVAcKGYCXL0DcaXDgrUyp5JM8wjH+FQoIYwwgORgBzYrvIvI2ta4OOjDnb9bQDcyjR7SqvP+UFUf9r225DK23BMLuYwOz3+2DKsW6t7Lvuns6Xmo2kmcPnw2yxP5+K65anLTipWA0n2340aUn2SUYimkGxZpgd7nHE1g4TK7SBcdPzeRiNRrJXZspdtkSlkK1LomY71iTi0H0uGYj3PZYt6WUv+tO675vDni3nDdGnOxcu55B8/KEyRur6D3RIldP6PTIc4ExrI="
        file_glob: true
        file: "adapter/build/distributions/*.zip"
        skip_cleanup: true
        name: "Version $TRAVIS_TAG"
        on:
          tags: true
          repo: fwcd/kotlin-debug-adapter
